// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: getchirpsbyuserid.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const getChirpsByUserID = `-- name: GetChirpsByUserID :one
SELECT id, created_at, updated_at, body, user_id FROM chirps
WHERE user_id = $1
ORDER BY created_at
`

func (q *Queries) GetChirpsByUserID(ctx context.Context, userID uuid.UUID) (Chirp, error) {
	row := q.db.QueryRowContext(ctx, getChirpsByUserID, userID)
	var i Chirp
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Body,
		&i.UserID,
	)
	return i, err
}
