// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: getusers.sql

package database

import (
	"context"
)

const getUsers = `-- name: GetUsers :exec
SELECT id, created_at, updated_at, body, user_id FROM chirps
ORDER BY created_at ASC
`

func (q *Queries) GetUsers(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, getUsers)
	return err
}
