// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: inserttokens.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const insertTokenToDatabase = `-- name: InsertTokenToDatabase :one
INSERT INTO refresh_tokens (token, created_at, updated_at, user_id, expires_at)
VALUES (
    $1,
    NOW(),
    NOW(),
    $2,
    NOW() + INTERVAL '60 days'
)
RETURNING token, created_at, updated_at, user_id, expires_at, revoked_at
`

type InsertTokenToDatabaseParams struct {
	Token  string
	UserID uuid.UUID
}

func (q *Queries) InsertTokenToDatabase(ctx context.Context, arg InsertTokenToDatabaseParams) (RefreshToken, error) {
	row := q.db.QueryRowContext(ctx, insertTokenToDatabase, arg.Token, arg.UserID)
	var i RefreshToken
	err := row.Scan(
		&i.Token,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}
