// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: revokeuserrefreshtoken.sql

package database

import (
	"context"
)

const revokeUserRefreshToken = `-- name: RevokeUserRefreshToken :exec
UPDATE refresh_tokens
SET revoked_at = NOW(), updated_at = NOW()
WHERE token = $1
`

func (q *Queries) RevokeUserRefreshToken(ctx context.Context, token string) error {
	_, err := q.db.ExecContext(ctx, revokeUserRefreshToken, token)
	return err
}
